#!/bin/sh 
SRC_DIR=$(pwd)
WORK_DIR=$(mktemp -d)
MAKE=gmake

# Needed to build p4est on FreeBSD
export LIBS=-lm

cleanup() {
  rm -rf "$WORK_DIR"
  echo ""
  echo "Deleted working directory $WORK_DIR"
}
trap cleanup EXIT

echo "Building p4est tarball in $WORK_DIR"
echo ""
# Get p4est
cd "$WORK_DIR" || exit
git clone --recursive  --branch tisaac/hotfix-p6est-lnodes https://github.com/tisaac/p4est
cd p4est || exit

# Setup exclude files so that version number is not dirty
./bootstrap
./configure
git ls-files --others --exclude-standard >> .git/info/exclude
GIT_DIR=.git/modules/sc git ls-files --others --exclude-standard >> .git/modules/sc/info/exclude
echo ChangeLog >> .git/info/exclude
echo ChangeLog >> .git/modules/sc/info/exclude
git clean -xdf
git submodule foreach git clean -xdf

# Configure and build distribution tarball
./bootstrap
./configure

echo ""
echo "Building versions"
echo ""
git describe --dirty
git submodule foreach git describe --dirty
echo ""

$MAKE -j distcheck
cp p4est-*.tar.gz "$SRC_DIR"
